// AUTO-GENERATED by scripts/build-portfolio-data.mjs
// Do not edit by hand. Re-run the script after adding/removing images.
import type { ImageMetadata } from "astro";

import p01 from "@assets/portfolio/portfolio-07.jpg";
import p02 from "@assets/portfolio/portfolio-18.jpg";
import p03 from "@assets/portfolio/portfolio-30.jpg";
import p04 from "@assets/portfolio/portfolio-04.jpg";
import p05 from "@assets/portfolio/portfolio-36.jpg";
import p06 from "@assets/portfolio/portfolio-32.jpg";
import p07 from "@assets/portfolio/portfolio-16.jpg";
import p08 from "@assets/portfolio/portfolio-52.jpg";
import p09 from "@assets/portfolio/portfolio-55.jpg";
import p10 from "@assets/portfolio/portfolio-44.jpg";
import p11 from "@assets/portfolio/portfolio-57.jpg";
import p12 from "@assets/portfolio/portfolio-06.jpg";
import p13 from "@assets/portfolio/portfolio-12.jpg";
import p14 from "@assets/portfolio/portfolio-31.jpg";
import p15 from "@assets/portfolio/portfolio-27.jpg";
import p16 from "@assets/portfolio/portfolio-29.jpg";
import p17 from "@assets/portfolio/portfolio-39.jpg";
import p18 from "@assets/portfolio/portfolio-41.jpg";
import p19 from "@assets/portfolio/portfolio-17.jpg";
import p20 from "@assets/portfolio/portfolio-50.jpg";
import p21 from "@assets/portfolio/portfolio-14.jpg";
import p22 from "@assets/portfolio/portfolio-34.jpg";
import p23 from "@assets/portfolio/portfolio-08.jpg";
import p24 from "@assets/portfolio/portfolio-02.jpg";
import p25 from "@assets/portfolio/portfolio-37.jpg";
import p26 from "@assets/portfolio/portfolio-51.jpg";
import p27 from "@assets/portfolio/portfolio-42.jpg";
import p28 from "@assets/portfolio/portfolio-23.jpg";
import p29 from "@assets/portfolio/portfolio-58.jpg";
import p30 from "@assets/portfolio/portfolio-60.jpg";
import p31 from "@assets/portfolio/portfolio-59.jpg";
import p32 from "@assets/portfolio/portfolio-54.jpg";
import p33 from "@assets/portfolio/portfolio-22.jpg";
import p34 from "@assets/portfolio/portfolio-35.jpg";
import p35 from "@assets/portfolio/portfolio-48.jpg";
import p36 from "@assets/portfolio/portfolio-45.jpg";
import p37 from "@assets/portfolio/portfolio-49.jpg";
import p38 from "@assets/portfolio/portfolio-10.jpg";
import p39 from "@assets/portfolio/portfolio-46.jpg";
import p40 from "@assets/portfolio/portfolio-05.jpg";
import p41 from "@assets/portfolio/portfolio-33.jpg";
import p42 from "@assets/portfolio/portfolio-20.jpg";
import p43 from "@assets/portfolio/portfolio-43.jpg";
import p44 from "@assets/portfolio/portfolio-15.jpg";
import p45 from "@assets/portfolio/portfolio-09.jpg";
import p46 from "@assets/portfolio/portfolio-19.jpg";
import p47 from "@assets/portfolio/portfolio-01.jpg";
import p48 from "@assets/portfolio/portfolio-53.jpg";
import p49 from "@assets/portfolio/portfolio-40.jpg";
import p50 from "@assets/portfolio/portfolio-24.jpg";
import p51 from "@assets/portfolio/portfolio-26.jpg";
import p52 from "@assets/portfolio/portfolio-25.jpg";
import p53 from "@assets/portfolio/portfolio-56.jpg";
import p54 from "@assets/portfolio/portfolio-28.jpg";
import p55 from "@assets/portfolio/portfolio-38.jpg";
import p56 from "@assets/portfolio/portfolio-47.jpg";
import p57 from "@assets/portfolio/portfolio-13.jpg";
import p58 from "@assets/portfolio/portfolio-21.jpg";
import p59 from "@assets/portfolio/portfolio-03.jpg";
import p60 from "@assets/portfolio/portfolio-11.jpg";

export type PortfolioRatio = "portrait" | "landscape";

export type PortfolioImage = {
  image: ImageMetadata;
  alt: string;
  ratio: PortfolioRatio;
  /** Intrinsic width in px (for srcset hints) */
  width: number;
  /** Intrinsic height in px (for srcset hints) */
  height: number;
  /** Pre-assigned column (1..N) for explicit masonry layout */
  column: number;
};

export const NUM_COLUMNS = 4;

export const portfolio: PortfolioImage[] = [
  { image: p01, alt: "Editorial wedding photograph 01", ratio: "landscape", width: 1600, height: 1067, column: 1 },
  { image: p02, alt: "Editorial wedding photograph 02", ratio: "portrait", width: 1066, height: 1600, column: 1 },
  { image: p03, alt: "Editorial wedding photograph 03", ratio: "portrait", width: 1066, height: 1600, column: 1 },
  { image: p04, alt: "Editorial wedding photograph 04", ratio: "portrait", width: 1600, height: 2400, column: 1 },
  { image: p05, alt: "Editorial wedding photograph 05", ratio: "landscape", width: 1600, height: 1067, column: 1 },
  { image: p06, alt: "Editorial wedding photograph 06", ratio: "portrait", width: 1600, height: 2400, column: 1 },
  { image: p07, alt: "Editorial wedding photograph 07", ratio: "portrait", width: 1600, height: 2400, column: 1 },
  { image: p08, alt: "Editorial wedding photograph 08", ratio: "portrait", width: 1600, height: 2400, column: 1 },
  { image: p09, alt: "Editorial wedding photograph 09", ratio: "landscape", width: 1600, height: 1067, column: 1 },
  { image: p10, alt: "Editorial wedding photograph 10", ratio: "portrait", width: 1067, height: 1600, column: 1 },
  { image: p11, alt: "Editorial wedding photograph 11", ratio: "portrait", width: 1067, height: 1600, column: 1 },
  { image: p12, alt: "Editorial wedding photograph 12", ratio: "landscape", width: 1600, height: 1067, column: 1 },
  { image: p13, alt: "Editorial wedding photograph 13", ratio: "portrait", width: 1067, height: 1600, column: 1 },
  { image: p14, alt: "Editorial wedding photograph 14", ratio: "portrait", width: 1067, height: 1600, column: 1 },
  { image: p15, alt: "Editorial wedding photograph 15", ratio: "portrait", width: 1067, height: 1600, column: 1 },
  { image: p16, alt: "Editorial wedding photograph 16", ratio: "portrait", width: 1066, height: 1600, column: 2 },
  { image: p17, alt: "Editorial wedding photograph 17", ratio: "landscape", width: 1772, height: 1181, column: 2 },
  { image: p18, alt: "Editorial wedding photograph 18", ratio: "portrait", width: 1600, height: 2400, column: 2 },
  { image: p19, alt: "Editorial wedding photograph 19", ratio: "portrait", width: 1600, height: 2400, column: 2 },
  { image: p20, alt: "Editorial wedding photograph 20", ratio: "portrait", width: 1600, height: 2400, column: 2 },
  { image: p21, alt: "Editorial wedding photograph 21", ratio: "landscape", width: 1600, height: 1066, column: 2 },
  { image: p22, alt: "Editorial wedding photograph 22", ratio: "portrait", width: 1600, height: 2400, column: 2 },
  { image: p23, alt: "Editorial wedding photograph 23", ratio: "portrait", width: 1600, height: 2400, column: 2 },
  { image: p24, alt: "Editorial wedding photograph 24", ratio: "landscape", width: 2400, height: 1800, column: 2 },
  { image: p25, alt: "Editorial wedding photograph 25", ratio: "portrait", width: 1067, height: 1600, column: 2 },
  { image: p26, alt: "Editorial wedding photograph 26", ratio: "portrait", width: 1067, height: 1600, column: 2 },
  { image: p27, alt: "Editorial wedding photograph 27", ratio: "portrait", width: 1067, height: 1600, column: 2 },
  { image: p28, alt: "Editorial wedding photograph 28", ratio: "landscape", width: 2400, height: 1600, column: 2 },
  { image: p29, alt: "Editorial wedding photograph 29", ratio: "portrait", width: 1067, height: 1600, column: 2 },
  { image: p30, alt: "Editorial wedding photograph 30", ratio: "portrait", width: 1067, height: 1600, column: 2 },
  { image: p31, alt: "Editorial wedding photograph 31", ratio: "portrait", width: 1066, height: 1600, column: 3 },
  { image: p32, alt: "Editorial wedding photograph 32", ratio: "portrait", width: 1066, height: 1600, column: 3 },
  { image: p33, alt: "Editorial wedding photograph 33", ratio: "landscape", width: 1600, height: 1066, column: 3 },
  { image: p34, alt: "Editorial wedding photograph 34", ratio: "portrait", width: 1600, height: 2400, column: 3 },
  { image: p35, alt: "Editorial wedding photograph 35", ratio: "portrait", width: 1600, height: 2400, column: 3 },
  { image: p36, alt: "Editorial wedding photograph 36", ratio: "portrait", width: 1600, height: 2400, column: 3 },
  { image: p37, alt: "Editorial wedding photograph 37", ratio: "landscape", width: 1600, height: 1067, column: 3 },
  { image: p38, alt: "Editorial wedding photograph 38", ratio: "portrait", width: 1600, height: 2400, column: 3 },
  { image: p39, alt: "Editorial wedding photograph 39", ratio: "portrait", width: 1067, height: 1600, column: 3 },
  { image: p40, alt: "Editorial wedding photograph 40", ratio: "landscape", width: 1600, height: 1067, column: 3 },
  { image: p41, alt: "Editorial wedding photograph 41", ratio: "portrait", width: 1067, height: 1600, column: 3 },
  { image: p42, alt: "Editorial wedding photograph 42", ratio: "portrait", width: 1067, height: 1600, column: 3 },
  { image: p43, alt: "Editorial wedding photograph 43", ratio: "portrait", width: 1067, height: 1600, column: 3 },
  { image: p44, alt: "Editorial wedding photograph 44", ratio: "landscape", width: 1600, height: 1067, column: 3 },
  { image: p45, alt: "Editorial wedding photograph 45", ratio: "portrait", width: 1067, height: 1600, column: 3 },
  { image: p46, alt: "Editorial wedding photograph 46", ratio: "portrait", width: 1066, height: 1600, column: 4 },
  { image: p47, alt: "Editorial wedding photograph 47", ratio: "portrait", width: 1066, height: 1600, column: 4 },
  { image: p48, alt: "Editorial wedding photograph 48", ratio: "portrait", width: 1600, height: 2400, column: 4 },
  { image: p49, alt: "Editorial wedding photograph 49", ratio: "portrait", width: 1600, height: 2400, column: 4 },
  { image: p50, alt: "Editorial wedding photograph 50", ratio: "landscape", width: 1600, height: 1067, column: 4 },
  { image: p51, alt: "Editorial wedding photograph 51", ratio: "portrait", width: 1600, height: 2400, column: 4 },
  { image: p52, alt: "Editorial wedding photograph 52", ratio: "portrait", width: 1600, height: 2400, column: 4 },
  { image: p53, alt: "Editorial wedding photograph 53", ratio: "portrait", width: 1600, height: 2400, column: 4 },
  { image: p54, alt: "Editorial wedding photograph 54", ratio: "portrait", width: 1067, height: 1600, column: 4 },
  { image: p55, alt: "Editorial wedding photograph 55", ratio: "landscape", width: 1772, height: 1181, column: 4 },
  { image: p56, alt: "Editorial wedding photograph 56", ratio: "portrait", width: 1067, height: 1600, column: 4 },
  { image: p57, alt: "Editorial wedding photograph 57", ratio: "portrait", width: 1067, height: 1600, column: 4 },
  { image: p58, alt: "Editorial wedding photograph 58", ratio: "portrait", width: 1067, height: 1600, column: 4 },
  { image: p59, alt: "Editorial wedding photograph 59", ratio: "portrait", width: 1800, height: 2400, column: 4 },
  { image: p60, alt: "Editorial wedding photograph 60", ratio: "landscape", width: 1600, height: 1067, column: 4 },
];
